//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRucula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class draco
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string Author { get; set; }
        public string Date { get; set; }
        public string Medium { get; set; }
        public string Recipient { get; set; }
    }
}
